Repository KDT3-miniproject-team1/backend, pull requests merged in 2023-02, with the labels that each got.

#8 conf: LoanRate와 LoanProduct의 관계 재설정 (One to Many 양방향 설정)
  src/main/java/com/miniproject/backend/loanproduct/domain/LoanProduct.java
  src/main/java/com/miniproject/backend/loanproduct/domain/LoanRate.java
Labels: Priority : High, Status : Completed, Type : Config

#9 Feature/sign in 회원가입 기능 구현
  src/main/java/com/miniproject/backend/global/config/SecurityConfig.java
  src/main/java/com/miniproject/backend/user/controller/UserController.java
  src/main/java/com/miniproject/backend/user/domain/User.java
  src/main/java/com/miniproject/backend/user/dto/UserRequestDTO.java
  src/main/java/com/miniproject/backend/user/repository/UserRepository.java
  src/main/java/com/miniproject/backend/user/service/UserService.java
  src/main/java/com/miniproject/backend/user/service/UserServiceImpl.java
Labels: Priority : High

#10 Feature/sign in exception 회원가입 exception 추가
  src/main/java/com/miniproject/backend/global/exception/CustomExceptionHandler.java
  src/main/java/com/miniproject/backend/user/controller/UserController.java
  src/main/java/com/miniproject/backend/user/exception/UserException.java
  src/main/java/com/miniproject/backend/user/exception/UserExceptionType.java
  src/main/java/com/miniproject/backend/user/service/UserServiceImpl.java
Labels: Priority : Low

#18 Feature/like 관심상품 등록 exception 추가
  src/main/java/com/miniproject/backend/global/exception/CustomExceptionHandler.java
  src/main/java/com/miniproject/backend/like/controller/LikeController.java
  src/main/java/com/miniproject/backend/like/exception/LikeException.java
  src/main/java/com/miniproject/backend/like/exception/LikeExceptionType.java
  src/main/java/com/miniproject/backend/like/repository/LikeRepository.java
  src/main/java/com/miniproject/backend/like/service/LikeServiceImpl.java
  src/main/java/com/miniproject/backend/loanproduct/exception/ProductException.java
  src/main/java/com/miniproject/backend/loanproduct/exception/ProductExceptionType.java
  src/main/java/com/miniproject/backend/loanproduct/service/impl/ProductServiceImpl.java
  src/main/java/com/miniproject/backend/user/exception/UserExceptionType.java
  src/main/java/com/miniproject/backend/user/service/UserServiceImpl.java
Labels: For : API, Priority : Medium, Type : Feature, Type : Config

#43 Feature/jwt 설정파일
  src/main/java/com/miniproject/backend/global/jwt/CustomUserDetails.java
  src/main/java/com/miniproject/backend/global/jwt/JwtAuthorizationFilter.java
  src/main/java/com/miniproject/backend/global/jwt/JwtConfig.java
  src/main/java/com/miniproject/backend/global/jwt/JwtType.java
  src/main/java/com/miniproject/backend/global/jwt/auth/AuthToken.java
  src/main/java/com/miniproject/backend/global/jwt/auth/AuthTokenProvider.java
Labels: Priority : High, Status : Completed, Type : Config

#47 Feature/security config
  src/main/java/com/miniproject/backend/global/config/SecurityConfig.java
  src/main/java/com/miniproject/backend/global/config/SwaggerConfig.java
  src/main/java/com/miniproject/backend/global/config/WebMvcConfig.java
  src/main/java/com/miniproject/backend/global/jwt/CustomUserDetails.java
  src/main/java/com/miniproject/backend/user/controller/LoginController.java
Labels: Priority : High, Status : Completed, Type : Config

#50 Feature/user update
  src/main/java/com/miniproject/backend/user/controller/UserController.java
  src/main/java/com/miniproject/backend/user/domain/User.java
  src/main/java/com/miniproject/backend/user/dto/LoginRequestDTO.java
  src/main/java/com/miniproject/backend/user/service/UserService.java
  src/main/java/com/miniproject/backend/user/service/UserServiceImpl.java
Labels: For : API, Priority : Low, Status : Completed, Type : Feature

#54 Feature/like 관심상품 DTO Inner class 생성 및 적용
  src/main/java/com/miniproject/backend/like/controller/LikeController.java
  src/main/java/com/miniproject/backend/like/dto/LikeDto.java
  src/main/java/com/miniproject/backend/like/dto/LikeRequestDto.java
  src/main/java/com/miniproject/backend/like/dto/LikeResponseDto.java
  src/main/java/com/miniproject/backend/like/service/LikeService.java
  src/main/java/com/miniproject/backend/like/service/LikeServiceImpl.java
Labels: For : API, Priority : Low, Status : In progress, Type : Refactory

#75 Feature/token 로그인 시 refreshtoken 쿠키 저장 및 reissue 기능 구현
  src/main/java/com/miniproject/backend/global/jwt/CookieProvider.java
  src/main/java/com/miniproject/backend/user/controller/LoginController.java
  src/main/java/com/miniproject/backend/user/domain/RefreshToken.java
  src/main/java/com/miniproject/backend/user/domain/User.java
  src/main/java/com/miniproject/backend/user/exception/UserExceptionType.java
  src/main/java/com/miniproject/backend/user/repository/TokenRepository.java
  src/main/java/com/miniproject/backend/user/service/LoginService.java
  src/main/java/com/miniproject/backend/user/service/TokenService.java
  src/main/java/com/miniproject/backend/user/service/impl/LoginServiceImpl.java
  src/main/java/com/miniproject/backend/user/service/impl/TokenServiceImpl.java
Labels: For : API, Priority : High, Status : Completed, Type : Feature, Type : Refactory

#84 Feature/token 로그아웃 기능 구현
  src/main/java/com/miniproject/backend/user/controller/LoginController.java
  src/main/java/com/miniproject/backend/user/service/TokenService.java
  src/main/java/com/miniproject/backend/user/service/impl/TokenServiceImpl.java
Labels: For : API, Priority : Medium, Status : Completed, Type : Feature
